// apps/landing-page/src/ButtonGroup.tsx
import { FunctionComponent } from 'react';
import styles from '@libs/theme/buttonGroup.module.css';

export interface ButtonGroupProps {
  children: any
}

export const ButtonGroup: FunctionComponent<ButtonGroupProps> = ({ children }) => (
  <div className={styles.buttonGroup}>
    {children}
  </div>
);

// apps/ui/src/app/button-group.component.ts
import { Component, HostBinding } from '@angular/core';
import styles from '@libs/theme/buttonGroup.module.css';

@Component({
  selector: 'app-button-group',
  template: '<ng-content></ng-content>',
})
export class ButtonGroupComponent {
  @HostBinding('class')
  get classes() {
    return styles.buttonGroup;
  }
}
