// apps/landing-page/src/Button.tsx
import { FunctionComponent } from 'react';
import styles from '@libs/theme/button.module.css';

export interface ButtonProps {
  children: any;
  appearance?: string;
}

export const Button: FunctionComponent<ButtonProps> = ({ children, appearance = 'primary' }) => (
  <button className={styles[appearance]}>{children}</button>
);

// apps/ui/src/app/button.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import styles from '@libs/theme/button.module.css';

@Component({
  selector: 'button[appButton]',
  template: '<ng-content></ng-content>',
})
export class ButtonComponent {
  @Input()
  appearance = 'primary';

  @HostBinding('class')
  get classes(): string {
    return styles[this.appearance];
  }
}
